/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.gradle.toomanyfiles

import com.sun.management.UnixOperatingSystemMXBean
import spock.lang.Ignore
import spock.lang.Specification

import java.lang.management.ManagementFactory

@Ignore //ignored to allow creation of the application jar
class MaxOpenFilesTest extends Specification {
    def "can handle more than default allowed open files"() {
        expect:
        ((UnixOperatingSystemMXBean) ManagementFactory.getOperatingSystemMXBean()).getMaxFileDescriptorCount() > 20000
    }
}
