/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.gradle.toomanyfiles

import com.sun.management.UnixOperatingSystemMXBean
import spock.lang.Ignore
import spock.lang.Specification

import java.lang.management.ManagementFactory

class MaxOpenFilesTest extends Specification {
    def "can handle more than default allowed open files"() {
        expect:
        def maxFileDescriptorCount = ((UnixOperatingSystemMXBean) ManagementFactory.getOperatingSystemMXBean()).getMaxFileDescriptorCount()
        println "Test max files: $maxFileDescriptorCount"
        true
    }
}
